name: CI/CD

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  publish-permissions-minimal:
    name: Publish (minimal permissions)
    # we run the action from this branch whenever we can (when it runs in our repo's context)
    if: >
      always() &&
      github.event.sender.login != 'dependabot[bot]' &&
      ( github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository )
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy test junit xml files
        run: |
          mkdir -p test-files
          cp -v python/test/files/*.xml test-files/

      - name: Prepare publish action from this branch
        run: |
          sed --in-place "s/image: .*/image: 'Dockerfile'/" action.yml

      - name: Publish Unit Test Results
        uses: ./
        timeout-minutes: 5
        with:
          github_retries: 0
          comment_mode: off
          compare_to_earlier_commit: false
          check_name: Unit Test Results (minimal permissions)
          files: "test-files/**.xml"
          LOG_LEVEL: DEBUG
          ROOT_LOG_LEVEL: DEBUG

  publish-permissions-minimal-compare:
    name: Publish (minimal compare permissions)
    # we run the action from this branch whenever we can (when it runs in our repo's context)
    if: >
      always() &&
      github.event.sender.login != 'dependabot[bot]' &&
      ( github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository )
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy test junit xml files
        run: |
          mkdir -p test-files
          cp -v python/test/files/*.xml test-files/

      - name: Prepare publish action from this branch
        run: |
          sed --in-place "s/image: .*/image: 'Dockerfile'/" action.yml

      - name: Publish Unit Test Results
        uses: ./
        timeout-minutes: 5
        with:
          github_retries: 0
          comment_mode: off
          compare_to_earlier_commit: true
          check_name: Unit Test Results (minimal compare permissions)
          files: "test-files/**.xml"
          LOG_LEVEL: DEBUG
          ROOT_LOG_LEVEL: DEBUG

  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    steps:
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Event File
          path: ${{ github.event_path }}
